swagger: '2.0'
info:
  version: 1.0.0
  title: Discussions
  description: A new api for discussions
host: 'localhost:8080'
basePath: /api
schemes:
  - http
  - https
paths:
  '/discussion/{id}':
    get:
      description: get comments of discussion
      operationId: getDiscussion
      summary: Get a discussion
      produces:
        - application/json
      parameters:
        - name: id
          description: id of discussions
          in: path
          type: string
          required: true
      responses:
        '200':
          description: list if discussion
          schema:
            title: list of comment
            type: array
            items:
              $ref: '#/definitions/Comment'
        '404':
          description: discussion id doesn't exist
  '/discussion/{id_discussion}/comment/{id_comment}':
    get:
      description: get a Comment
      operationId: getComment
      summary: Get a comment
      produces:
        - application/json
      parameters:
        - name: id_discussion
          description: id of discussion
          in: path
          type: string
          required: true
        - name: id_comment
          description: id of comment
          in: path
          type: string
          required: true
      responses:
        '200':
          description: comment
          schema:
            title: searched comment
            type: object
            items:
              $ref: '#/definitions/Comment'
        '404':
          description: comment id doesn't exist
  /discussion:
    post:
      description: create a discussion
      operationId: createDiscussion
      summary: add a new discussion
      consumes:
        - application/json
      parameters:
        - name: comment
          in: body
          required: true
          schema:
            $ref: '#/definitions/Discussion'
      responses:
        '201':
          description: created
          schema:
            type: object
  '/discussion/{id_discussion}/comment':
    post:
      description: create a comment
      operationId: createComment
      summary: add a new comment
      consumes:
        - application/json
      parameters:
        - name: id_discussion
          in: path
          required: true
          type: string
        - name: comment
          in: body
          required: true
          schema:
            $ref: '#/definitions/Comment'
      responses:
        '201':
          description: created
          schema:
            type: object
definitions:
  Comment:
    type: object
    properties:
      id_comment:
        type: string
      comment:
        type: string
      like:
        type: integer
      dislike:
        type: integer
      date:
        type: string
        format: date-time
      author:
        type: string
      report:
        type: boolean
      father_url:
        type: string
  Discussion:
    type: object
    properties:
      id_discussion:
        type: string
      id_article:
        type: string