swagger: '2.0'
info:
  version: 1.0.0
  title: Discussions
  description: A new api for discussions
host: 'localhost:8080'
basePath: /api
schemes:
  - http
  - https
paths:
  '/discussions/{id}':
    get:
      description: get comments of discussion
      operationId: getDiscussion
      summary: Get a discussion
      parameters:
        - name: id
          description: id of discussions
          in: path
          type: integer
          required: true
      responses:
        '200':
          description: the discussion object
          schema:
            $ref: '#/definitions/Discussion'
        '404':
          description: discussion id doesn't exist
  '/discussions/{id}/comments/{id_comment}':
    get:
      description: get a Comment
      operationId: getComment
      summary: Get a comment
      parameters:
        - name: id
          description: id of discussion
          in: path
          type: integer
          required: true
        - name: id_comment
          description: id of comment
          in: path
          type: integer
          required: true
      responses:
        '200':
          description: comment
          schema:
            $ref: '#/definitions/Comment'
        '404':
          description: comment id doesn't exist
  /discussions:
    post:
      description: create a discussion
      operationId: createDiscussion
      summary: add a new discussion
      parameters:
        - name: comment
          in: body
          required: true
          schema:
            $ref: '#/definitions/Discussion'
      responses:
        '201':
          description: created
          schema:
            type: object
    get:
      description: get the list of all discussions
      operationId: getDiscussions
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Discussion'

  '/discussions/{id}/comments':
    post:
      description: create a comment
      operationId: createComment
      summary: add a new comment
      parameters:
        - name: id
          description: id of discussion
          in: path
          type: integer
          required: true
        - name: comment
          in: body
          required: true
          schema:
            $ref: '#/definitions/Comment'
      responses:
        '201':
          description: created
          schema:
            type: object
    get:
      description: get the list of all comments
      operationId: getComments
      summary: get comments of the discussion
      produces:
        - application/json
      parameters:
        - name: id
          description: id of discussions
          in: path
          type: integer
          required: true
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Comment'
definitions:
  Comment:
    type: object
    properties:
      id_comment:
        type: integer
      id_discussion:
        type: integer
      comment:
        type: string
      like:
        type: integer
      dislike:
        type: integer
      date:
        type: string
        format: date-time
      author:
        type: string
      report:
        type: boolean
      father_url:
        type: string
      discussion:
        type: object
        $ref: '#/definitions/Discussion'
  Discussion:
    type: object
    properties:
      id_discussion:
        type: integer
      id_article:
        type: integer
      comments:
        type: array
        items:
          type: object
          $ref: '#/definitions/Comment'