swagger: '2.0'
info:
  version: 1.0.0
  title: Discussions
  description: A new api for discussions
host: 'localhost:1111'
basePath: /api
schemes:
  - http
  - https
paths:
  '/discussions/{idDiscussion}':
    delete:
      description: Delete a discussion and all comments associated
      operationId: delDiscussion
      parameters:
        - name: idDiscussion
          description: id of discussion
          in: path
          type: integer
          required: true
      responses:
        '204':
          description: discussion deleted
        '404':
          description: Not found, discussion id doesn't exist
    get:
      description: Get a discussion with all details (comments, votes, reports)
      operationId: getDiscussion
      summary: Get a discussion
      parameters:
        - name: idDiscussion
          description: id of discussions
          in: path
          type: integer
          required: true
      responses:
        '200':
          description: the discussion object
          schema:
            $ref: '#/definitions/OutputDiscussion'
        '404':
          description: Not found, discussion id doesn't exist
  '/discussions/{idDiscussion}/comments/{idComment}':
    get:
      description: Get a Comment with all details (votes, reports)
      operationId: getComment
      summary: Get a comment
      parameters:
        - name: idDiscussion
          description: id of discussion
          in: path
          type: integer
          required: true
        - name: idComment
          description: id of comment
          in: path
          type: integer
          required: true
      responses:
        '200':
          description: comment
          schema:
            $ref: '#/definitions/OutputComment'
        '404':
          description: Not found, discussion id or comment id doesn't exist
    delete:
      description: Delete a comment in a discussion
      operationId: delComment
      parameters:
        - name: idDiscussion
          description: id of discussion
          in: path
          type: integer
          required: true
        - name: idComment
          description: id of comment
          in: path
          type: integer
          required: true
      responses:
        '204':
          description: comment deleted
        '404':
          description: Not found, discussion id or comment id doesn't exist
    put:
      description: Modify a comment in a discussion
      operationId: updateComment
      parameters:
        - name: idDiscussion
          in: path
          description: id of the discussion
          type: integer
          required: true
        - name: idComment
          description: id of comment
          in: path
          type: integer
          required: true
        - name: comment
          in: body
          description: comment to be updated
          required: true
          schema:
            $ref: '#/definitions/InputComment'
      responses:
        '204':
          description: comment modified
        '404':
          description: Not found, discussion id or comment id doesn't exist

  /discussions:
    post:
      description: Create a discussion linked to an article
      operationId: createDiscussion
      summary: add a new discussion
      parameters:
        - name: comment
          in: body
          required: true
          schema:
            $ref: '#/definitions/InputDiscussion'
      responses:
        '201':
          description: created
          schema:
            type: object
    get:
      description: get the list of all discussions with all details (comments, reports, votes)
      operationId: getDiscussions
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/OutputDiscussion'

  '/discussions/{idDiscussion}/comments':
    post:
      description: Create a comment in a discussion
      operationId: createComment
      summary: add a new comment
      parameters:
        - name: idDiscussion
          description: id of discussion
          in: path
          type: integer
          required: true
        - name: comment
          in: body
          required: true
          schema:
            $ref: '#/definitions/InputComment'
      responses:
        '201':
          description: created
          schema:
            type: object
        '404':
          description: Not found, discussion id doesn't exist

  '/discussions/{idDiscussion}/comments/{idComment}/votes':
    post:
      description: Vote a comment (rate)
      operationId: voteComment
      parameters:
        - name: idDiscussion
          description: id of discussion
          in: path
          type: integer
          required: true
        - name: idComment
          description: id of discussion
          in: path
          type: integer
          required: true
        - name: vote
          in: body
          required: true
          schema:
            $ref: '#/definitions/InputVote'
      responses:
        '201':
          description: created
          schema:
            type: object
        '404':
          description: Not found, discussion id or idComment doesn't exist

  '/discussions/{idDiscussion}/comments/{idComment}/reports':
    post:
      operationId: reportComment
      description: Vote a comment (rate)
      parameters:
        - name: idDiscussion
          description: id of discussion
          in: path
          type: integer
          required: true
        - name: idComment
          description: id of comment
          in: path
          type: integer
          required: true
        - name: report
          in: body
          required: true
          schema:
            $ref: '#/definitions/InputReport'
      responses:
        '201':
          description: created
          schema:
            type: object
        '404':
          description: Not found, discussion id or idComment doesn't exist

definitions:
  InputComment:
    type: object
    properties:
      comment:
        type: string
      father_url:
        type: string
  OutputComment:
    type: object
    properties:
      links:
        $ref: '#/definitions/OutputLinks'
      comment:
        type: string
      date:
        type: string
        format: date-time
      author:
        type: string
      votes:
        type: array
        items:
          $ref: '#/definitions/OutputVote'
      reports:
        type: array
        items:
          $ref: '#/definitions/OutputReport'
  InputDiscussion:
    type: object
    properties:
      id_article:
        type: integer
  OutputDiscussion:
    type: object
    properties:
      links:
        type: object
        properties:
          self:
            type: string
          related:
            type: string
      comments:
        type: array
        items:
          $ref: '#/definitions/OutputComment'
  InputVote:
    type: object
    properties:
      vote:
        type: boolean
  OutputVote:
    type: object
    properties:
      vote:
        type: boolean
      date:
        type: string
        format: date-time
      author:
        type: string
  InputReport:
    type: object
    properties:
       isReported:
         type: boolean
  OutputReport:
    type: object
    properties:
       isReported:
         type: boolean
       date:
          type: string
          format: date-time
       author:
          type: string

  OutputLinks:
    type: object
    properties:
      self:
        type: string
      related:
        type: string