swagger: '2.0'
info:
  version: 1.0.0
  title: Discussions
  description: A new api for discussions
host: 'localhost:8080'
basePath: /api
schemes:
  - http
  - https
paths:
  '/discussions/{id}':
    get:
      description: get comments of discussion
      operationId: getDiscussion
      summary: Get a discussion
      parameters:
        - name: id
          description: id of discussions
          in: path
          type: integer
          required: true
      responses:
        '200':
          description: the discussion object
          schema:
            $ref: '#/definitions/OutputDiscussion'
        '404':
          description: discussion id doesn't exist
  '/discussions/{id}/comments/{idComment}':
    get:
      description: get a Comment
      operationId: getComment
      summary: Get a comment
      parameters:
        - name: id
          description: id of discussion
          in: path
          type: integer
          required: true
        - name: idComment
          description: id of comment
          in: path
          type: integer
          required: true
      responses:
        '200':
          description: comment
          schema:
            $ref: '#/definitions/OutputComment'
        '404':
          description: comment id doesn't exist
    delete:
      description: del a comment in a discussion
      operationId: delComment
      parameters:
        - name: id
          description: id of discussion
          in: path
          type: integer
          required: true
        - name: idComment
          description: id of comment
          in: path
          type: integer
          required: true
      responses:
        '200':
          description: comment deleted
        '404':
          description: Not found

  /discussions:
    post:
      description: create a discussion
      operationId: createDiscussion
      summary: add a new discussion
      parameters:
        - name: comment
          in: body
          required: true
          schema:
            $ref: '#/definitions/InputDiscussion'
      responses:
        '201':
          description: created
          schema:
            type: object
    get:
      description: get the list of all discussions
      operationId: getDiscussions
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/OutputDiscussion'

  '/discussions/{id}/comments':
    post:
      description: create a comment
      operationId: createComment
      summary: add a new comment
      parameters:
        - name: id
          description: id of discussion
          in: path
          type: integer
          required: true
        - name: comment
          in: body
          required: true
          schema:
            $ref: '#/definitions/InputComment'
      responses:
        '201':
          description: created
          schema:
            type: object
    get:
      description: get the list of all comments
      operationId: getComments
      summary: get comments of the discussion
      produces:
        - application/json
      parameters:
        - name: id
          description: id of discussions
          in: path
          type: integer
          required: true
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/OutputComment'
    delete:
      description: del all comments in a discussion
      operationId: delComments
      parameters:
        - name: id
          description: id of discussion
          in: path
          type: integer
          required: true
      responses:
        '200':
          description: all comments deleted
        '404':
          description: Not found
definitions:
  InputComment:
    type: object
    properties:
      comment:
        type: string
      author:
        type: string
      father_url:
        type: string
  OutputComment:
    type: object
    properties:
      url_comment:
        string
      comment:
        type: string
      upScore:
        type: integer
      downScore:
        type: integer
      date:
        type: string
        format: date-time
      author:
        type: string
      report:
        type: boolean
      father_url:
        type: string
  InputDiscussion:
    type: object
    properties:
      id_article:
        type: integer
      comments:
        type: array
        items:
          type: object
          $ref: '#/definitions/InputComment'
  OutputDiscussion:
    type: object
    properties:
      url_discussion:
        type: string
      id_article:
        type: integer
      comments:
        type: array
        items:
          type: object
          $ref: '#/definitions/OutputComment'